// <auto-generated />
using System;
using KomunalkaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KomunalkaAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260206123334_RenameTariffPricingModelToName")]
    partial class RenameTariffPricingModelToName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KomunalkaAPI.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("address_type_id");

                    b.Property<string>("ApartmentNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("apartment_number");

                    b.Property<string>("BuildingNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("building_number");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<int>("RegionId")
                        .HasColumnType("integer")
                        .HasColumnName("region_id");

                    b.Property<int?>("ServiceCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("service_category_id");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("street");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("zip_code");

                    b.HasKey("Id")
                        .HasName("pk_addresses");

                    b.HasIndex("AddressTypeId")
                        .HasDatabaseName("ix_addresses_address_type_id");

                    b.HasIndex("RegionId")
                        .HasDatabaseName("ix_addresses_region_id");

                    b.HasIndex("ServiceCategoryId")
                        .HasDatabaseName("ix_addresses_service_category_id");

                    b.ToTable("addresses");
                });

            modelBuilder.Entity("KomunalkaAPI.Models.AddressType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_address_types");

                    b.ToTable("address_types");
                });

            modelBuilder.Entity("KomunalkaAPI.Models.AddressesServiceCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("integer")
                        .HasColumnName("address_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("ServiceCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("service_category_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_addresses_service_categories");

                    b.HasIndex("AddressId")
                        .HasDatabaseName("ix_addresses_service_categories_address_id");

                    b.HasIndex("ServiceCategoryId")
                        .HasDatabaseName("ix_addresses_service_categories_service_category_id");

                    b.ToTable("address_service_category", (string)null);
                });

            modelBuilder.Entity("KomunalkaAPI.Models.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Symbol")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("symbol");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_currencies");

                    b.ToTable("currencies");
                });

            modelBuilder.Entity("KomunalkaAPI.Models.Meter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("integer")
                        .HasColumnName("address_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<decimal?>("InitialReading")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("initial_reading");

                    b.Property<DateTime?>("InstallationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("installation_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Location")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("location");

                    b.Property<string>("ModelName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("model_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("PhotoPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("photo_path");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("serial_number");

                    b.Property<int?>("ServiceProviderId")
                        .HasColumnType("integer")
                        .HasColumnName("service_provider_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UtilityTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("utility_type_id");

                    b.HasKey("Id")
                        .HasName("pk_meters");

                    b.HasIndex("AddressId")
                        .HasDatabaseName("ix_meters_address_id");

                    b.HasIndex("ServiceProviderId")
                        .HasDatabaseName("ix_meters_service_provider_id");

                    b.HasIndex("UtilityTypeId")
                        .HasDatabaseName("ix_meters_utility_type_id");

                    b.ToTable("meters");
                });

            modelBuilder.Entity("KomunalkaAPI.Models.MeterReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Consumption")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("consumption");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsEstimated")
                        .HasColumnType("boolean")
                        .HasColumnName("is_estimated");

                    b.Property<int>("MeterId")
                        .HasColumnType("integer")
                        .HasColumnName("meter_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<decimal?>("PreviousReadingValue")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("previous_reading_value");

                    b.Property<DateTime>("ReadingDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reading_date");

                    b.Property<decimal>("ReadingValue")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("reading_value");

                    b.Property<int?>("TariffId")
                        .HasColumnType("integer")
                        .HasColumnName("tariff_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_meter_readings");

                    b.HasIndex("MeterId")
                        .HasDatabaseName("ix_meter_readings_meter_id");

                    b.HasIndex("TariffId")
                        .HasDatabaseName("ix_meter_readings_tariff_id");

                    b.ToTable("meter_readings");
                });

            modelBuilder.Entity("KomunalkaAPI.Models.MeterReadingImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_processed");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("mime_type");

                    b.Property<string>("OptimizedPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("optimized_path");

                    b.Property<long>("OptimizedSizeInBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("optimized_size_in_bytes");

                    b.Property<int>("ServiceCounterValueId")
                        .HasColumnType("integer")
                        .HasColumnName("service_counter_value_id");

                    b.Property<string>("ThumbnailPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("thumbnail_path");

                    b.Property<long>("ThumbnailSizeInBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("thumbnail_size_in_bytes");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_meter_reading_images");

                    b.HasIndex("ServiceCounterValueId")
                        .HasDatabaseName("ix_meter_reading_images_service_counter_value_id");

                    b.ToTable("meter_reading_images");
                });

            modelBuilder.Entity("KomunalkaAPI.Models.MeterReadingPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_processed");

                    b.Property<int>("MeterReadingId")
                        .HasColumnType("integer")
                        .HasColumnName("meter_reading_id");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("mime_type");

                    b.Property<string>("OptimizedPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("optimized_path");

                    b.Property<long>("OptimizedSizeInBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("optimized_size_in_bytes");

                    b.Property<string>("ThumbnailPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("thumbnail_path");

                    b.Property<long>("ThumbnailSizeInBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("thumbnail_size_in_bytes");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_meter_reading_photos");

                    b.HasIndex("MeterReadingId")
                        .HasDatabaseName("ix_meter_reading_photos_meter_reading_id");

                    b.ToTable("meter_reading_photos");
                });

            modelBuilder.Entity("KomunalkaAPI.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiry_date");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revoked");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_used");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens");
                });

            modelBuilder.Entity("KomunalkaAPI.Models.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_regions");

                    b.ToTable("regions");
                });

            modelBuilder.Entity("KomunalkaAPI.Models.ServiceCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_service_categories");

                    b.ToTable("service_categories");
                });

            modelBuilder.Entity("KomunalkaAPI.Models.ServiceCounter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("integer")
                        .HasColumnName("address_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text")
                        .HasColumnName("serial_number");

                    b.Property<int>("ServiceCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("service_category_id");

                    b.Property<int>("ServiceCounterMeasurementId")
                        .HasColumnType("integer")
                        .HasColumnName("service_counter_measurement_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_service_counters");

                    b.HasIndex("AddressId")
                        .HasDatabaseName("ix_service_counters_address_id");

                    b.HasIndex("ServiceCategoryId")
                        .HasDatabaseName("ix_service_counters_service_category_id");

                    b.HasIndex("ServiceCounterMeasurementId")
                        .HasDatabaseName("ix_service_counters_service_counter_measurement_id");

                    b.ToTable("service_counters");
                });

            modelBuilder.Entity("KomunalkaAPI.Models.ServiceCounterMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Measurement")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("measurement");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_service_counter_measurements");

                    b.ToTable("service_counter_measurements");
                });

            modelBuilder.Entity("KomunalkaAPI.Models.ServiceCounterValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("ServiceCounterId")
                        .HasColumnType("integer")
                        .HasColumnName("service_counter_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<float>("Value")
                        .HasColumnType("real")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_service_counter_values");

                    b.HasIndex("ServiceCounterId")
                        .HasDatabaseName("ix_service_counter_values_service_counter_id");

                    b.ToTable("service_counter_values");
                });

            modelBuilder.Entity("KomunalkaAPI.Models.ServiceProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("integer")
                        .HasColumnName("address_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UtilityTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("utility_type_id");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("pk_service_providers");

                    b.HasIndex("AddressId")
                        .HasDatabaseName("ix_service_providers_address_id");

                    b.HasIndex("UtilityTypeId")
                        .HasDatabaseName("ix_service_providers_utility_type_id");

                    b.ToTable("service_providers");
                });

            modelBuilder.Entity("KomunalkaAPI.Models.Tariff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseRate")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("base_rate");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("integer")
                        .HasColumnName("currency_id");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_to");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<decimal?>("ServiceFee")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("service_fee");

                    b.Property<int>("ServiceProviderId")
                        .HasColumnType("integer")
                        .HasColumnName("service_provider_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UtilityTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("utility_type_id");

                    b.HasKey("Id")
                        .HasName("pk_tariffs");

                    b.HasIndex("CurrencyId")
                        .HasDatabaseName("ix_tariffs_currency_id");

                    b.HasIndex("ServiceProviderId")
                        .HasDatabaseName("ix_tariffs_service_provider_id");

                    b.HasIndex("UtilityTypeId")
                        .HasDatabaseName("ix_tariffs_utility_type_id");

                    b.ToTable("tariffs");
                });

            modelBuilder.Entity("KomunalkaAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthProvider")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("auth_provider");

                    b.Property<int?>("AvatarHeight")
                        .HasColumnType("integer")
                        .HasColumnName("avatar_height");

                    b.Property<string>("AvatarMimeType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("avatar_mime_type");

                    b.Property<string>("AvatarOptimizedPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatar_optimized_path");

                    b.Property<long?>("AvatarSizeInBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("avatar_size_in_bytes");

                    b.Property<string>("AvatarThumbnailPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatar_thumbnail_path");

                    b.Property<int?>("AvatarWidth")
                        .HasColumnType("integer")
                        .HasColumnName("avatar_width");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("email_verified");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("external_id");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex(new[] { "AuthProvider", "ExternalId" }, "IX_User_Provider_ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_provider_external_id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("KomunalkaAPI.Models.UserAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("integer")
                        .HasColumnName("address_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_address_user");

                    b.HasIndex("AddressId")
                        .HasDatabaseName("ix_address_user_address_id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("is_primary = true");

                    b.HasIndex("UserId", "AddressId")
                        .IsUnique();

                    b.ToTable("address_user");
                });

            modelBuilder.Entity("KomunalkaAPI.Models.UtilityType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("slug");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_utility_types");

                    b.ToTable("utility_types");
                });

            modelBuilder.Entity("KomunalkaAPI.Models.Address", b =>
                {
                    b.HasOne("KomunalkaAPI.Models.AddressType", "AddressType")
                        .WithMany("Addresses")
                        .HasForeignKey("AddressTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_addresses_address_types_address_type_id");

                    b.HasOne("KomunalkaAPI.Models.Region", "Region")
                        .WithMany("Addresses")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_addresses_regions_region_id");

                    b.HasOne("KomunalkaAPI.Models.ServiceCategory", null)
                        .WithMany("Addresses")
                        .HasForeignKey("ServiceCategoryId")
                        .HasConstraintName("fk_addresses_service_categories_service_category_id");

                    b.Navigation("AddressType");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("KomunalkaAPI.Models.AddressesServiceCategory", b =>
                {
                    b.HasOne("KomunalkaAPI.Models.Address", "Address")
                        .WithMany("AddressesServiceCategories")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_addresses_service_categories_addresses_address_id");

                    b.HasOne("KomunalkaAPI.Models.ServiceCategory", "ServiceCategory")
                        .WithMany()
                        .HasForeignKey("ServiceCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_addresses_service_categories_service_categories_service_cate~");

                    b.Navigation("Address");

                    b.Navigation("ServiceCategory");
                });

            modelBuilder.Entity("KomunalkaAPI.Models.Meter", b =>
                {
                    b.HasOne("KomunalkaAPI.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_meters_addresses_address_id");

                    b.HasOne("KomunalkaAPI.Models.ServiceProvider", "ServiceProvider")
                        .WithMany("Meters")
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_meters_service_providers_service_provider_id");

                    b.HasOne("KomunalkaAPI.Models.UtilityType", "UtilityType")
                        .WithMany("Meters")
                        .HasForeignKey("UtilityTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_meters_utility_types_utility_type_id");

                    b.Navigation("Address");

                    b.Navigation("ServiceProvider");

                    b.Navigation("UtilityType");
                });

            modelBuilder.Entity("KomunalkaAPI.Models.MeterReading", b =>
                {
                    b.HasOne("KomunalkaAPI.Models.Meter", "Meter")
                        .WithMany()
                        .HasForeignKey("MeterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_meter_readings_meters_meter_id");

                    b.HasOne("KomunalkaAPI.Models.Tariff", "Tariff")
                        .WithMany()
                        .HasForeignKey("TariffId")
                        .HasConstraintName("fk_meter_readings_tariffs_tariff_id");

                    b.Navigation("Meter");

                    b.Navigation("Tariff");
                });

            modelBuilder.Entity("KomunalkaAPI.Models.MeterReadingImage", b =>
                {
                    b.HasOne("KomunalkaAPI.Models.ServiceCounterValue", "ServiceCounterValue")
                        .WithMany("Images")
                        .HasForeignKey("ServiceCounterValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_meter_reading_images_service_counter_values_service_counter_v~");

                    b.Navigation("ServiceCounterValue");
                });

            modelBuilder.Entity("KomunalkaAPI.Models.MeterReadingPhoto", b =>
                {
                    b.HasOne("KomunalkaAPI.Models.MeterReading", "MeterReading")
                        .WithMany("Photos")
                        .HasForeignKey("MeterReadingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_meter_reading_photos_meter_readings_meter_reading_id");

                    b.Navigation("MeterReading");
                });

            modelBuilder.Entity("KomunalkaAPI.Models.RefreshToken", b =>
                {
                    b.HasOne("KomunalkaAPI.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KomunalkaAPI.Models.ServiceCounter", b =>
                {
                    b.HasOne("KomunalkaAPI.Models.Address", null)
                        .WithMany("ServiceCounters")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_counters_addresses_address_id");

                    b.HasOne("KomunalkaAPI.Models.ServiceCategory", "ServiceCategory")
                        .WithMany()
                        .HasForeignKey("ServiceCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_counters_service_categories_service_category_id");

                    b.HasOne("KomunalkaAPI.Models.ServiceCounterMeasurement", "ServiceCounterMeasurement")
                        .WithMany()
                        .HasForeignKey("ServiceCounterMeasurementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_counters_service_counter_measurements_service_counter~");

                    b.Navigation("ServiceCategory");

                    b.Navigation("ServiceCounterMeasurement");
                });

            modelBuilder.Entity("KomunalkaAPI.Models.ServiceCounterValue", b =>
                {
                    b.HasOne("KomunalkaAPI.Models.ServiceCounter", "ServiceCounter")
                        .WithMany()
                        .HasForeignKey("ServiceCounterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_counter_values_service_counters_service_counter_id");

                    b.Navigation("ServiceCounter");
                });

            modelBuilder.Entity("KomunalkaAPI.Models.ServiceProvider", b =>
                {
                    b.HasOne("KomunalkaAPI.Models.Address", "Address")
                        .WithMany("ServiceProviders")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_providers_addresses_address_id");

                    b.HasOne("KomunalkaAPI.Models.UtilityType", "UtilityType")
                        .WithMany("ServiceProviders")
                        .HasForeignKey("UtilityTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_service_providers_utility_types_utility_type_id");

                    b.Navigation("Address");

                    b.Navigation("UtilityType");
                });

            modelBuilder.Entity("KomunalkaAPI.Models.Tariff", b =>
                {
                    b.HasOne("KomunalkaAPI.Models.Currency", "Currency")
                        .WithMany("Tariffs")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tariffs_currencies_currency_id");

                    b.HasOne("KomunalkaAPI.Models.ServiceProvider", "ServiceProvider")
                        .WithMany("Tariffs")
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tariffs_service_providers_service_provider_id");

                    b.HasOne("KomunalkaAPI.Models.UtilityType", "UtilityType")
                        .WithMany("Tariffs")
                        .HasForeignKey("UtilityTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tariffs_utility_types_utility_type_id");

                    b.Navigation("Currency");

                    b.Navigation("ServiceProvider");

                    b.Navigation("UtilityType");
                });

            modelBuilder.Entity("KomunalkaAPI.Models.UserAddress", b =>
                {
                    b.HasOne("KomunalkaAPI.Models.Address", "Address")
                        .WithMany("UserAddresses")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_address_user_addresses_address_id");

                    b.HasOne("KomunalkaAPI.Models.User", "User")
                        .WithMany("UserAddresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_address_user_users_user_id");

                    b.Navigation("Address");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KomunalkaAPI.Models.Address", b =>
                {
                    b.Navigation("AddressesServiceCategories");

                    b.Navigation("ServiceCounters");

                    b.Navigation("ServiceProviders");

                    b.Navigation("UserAddresses");
                });

            modelBuilder.Entity("KomunalkaAPI.Models.AddressType", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("KomunalkaAPI.Models.Currency", b =>
                {
                    b.Navigation("Tariffs");
                });

            modelBuilder.Entity("KomunalkaAPI.Models.MeterReading", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("KomunalkaAPI.Models.Region", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("KomunalkaAPI.Models.ServiceCategory", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("KomunalkaAPI.Models.ServiceCounterValue", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("KomunalkaAPI.Models.ServiceProvider", b =>
                {
                    b.Navigation("Meters");

                    b.Navigation("Tariffs");
                });

            modelBuilder.Entity("KomunalkaAPI.Models.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserAddresses");
                });

            modelBuilder.Entity("KomunalkaAPI.Models.UtilityType", b =>
                {
                    b.Navigation("Meters");

                    b.Navigation("ServiceProviders");

                    b.Navigation("Tariffs");
                });
#pragma warning restore 612, 618
        }
    }
}
