CREATE TABLE IF NOT EXISTS "migrations" ("id" integer primary key autoincrement not null, "migration" varchar not null, "batch" integer not null);
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE IF NOT EXISTS "users" ("id" integer primary key autoincrement not null, "name" varchar not null, "email" varchar not null, "email_verified_at" datetime, "password" varchar not null, "remember_token" varchar, "created_at" datetime, "updated_at" datetime);
CREATE UNIQUE INDEX "users_email_unique" on "users" ("email");
CREATE TABLE IF NOT EXISTS "password_reset_tokens" ("email" varchar not null, "token" varchar not null, "created_at" datetime, primary key ("email"));
CREATE TABLE IF NOT EXISTS "sessions" ("id" varchar not null, "user_id" integer, "ip_address" varchar, "user_agent" text, "payload" text not null, "last_activity" integer not null, primary key ("id"));
CREATE INDEX "sessions_user_id_index" on "sessions" ("user_id");
CREATE INDEX "sessions_last_activity_index" on "sessions" ("last_activity");
CREATE TABLE IF NOT EXISTS "cache" ("key" varchar not null, "value" text not null, "expiration" integer not null, primary key ("key"));
CREATE TABLE IF NOT EXISTS "cache_locks" ("key" varchar not null, "owner" varchar not null, "expiration" integer not null, primary key ("key"));
CREATE TABLE IF NOT EXISTS "jobs" ("id" integer primary key autoincrement not null, "queue" varchar not null, "payload" text not null, "attempts" integer not null, "reserved_at" integer, "available_at" integer not null, "created_at" integer not null);
CREATE INDEX "jobs_queue_index" on "jobs" ("queue");
CREATE TABLE IF NOT EXISTS "job_batches" ("id" varchar not null, "name" varchar not null, "total_jobs" integer not null, "pending_jobs" integer not null, "failed_jobs" integer not null, "failed_job_ids" text not null, "options" text, "cancelled_at" integer, "created_at" integer not null, "finished_at" integer, primary key ("id"));
CREATE TABLE IF NOT EXISTS "failed_jobs" ("id" integer primary key autoincrement not null, "uuid" varchar not null, "connection" text not null, "queue" text not null, "payload" text not null, "exception" text not null, "failed_at" datetime not null default CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX "failed_jobs_uuid_unique" on "failed_jobs" ("uuid");
CREATE TABLE IF NOT EXISTS "utility_types" ("id" integer primary key autoincrement not null, "slug" varchar not null, "unit" varchar not null, "description" text, "is_active" tinyint(1) not null default '1', "created_at" datetime, "updated_at" datetime, "display_name" varchar not null);
CREATE UNIQUE INDEX "utility_types_name_unique" on "utility_types" ("slug");
CREATE TABLE IF NOT EXISTS "meters" ("id" integer primary key autoincrement not null, "address_id" integer not null, "utility_type_id" integer not null, "serial_number" varchar, "name" varchar not null, "description" text, "is_active" tinyint(1) not null default '1', "created_at" datetime, "updated_at" datetime, foreign key("address_id") references "addresses"("id") on delete cascade, foreign key("utility_type_id") references "utility_types"("id") on delete cascade);
CREATE INDEX "meters_address_id_utility_type_id_index" on "meters" ("address_id", "utility_type_id");
CREATE INDEX "meters_address_id_is_active_index" on "meters" ("address_id", "is_active");
CREATE TABLE IF NOT EXISTS "currencies" ("id" integer primary key autoincrement not null, "code" varchar not null, "name" varchar not null, "symbol" varchar, "created_at" datetime, "updated_at" datetime);
CREATE INDEX "currencies_name_index" on "currencies" ("name");
CREATE UNIQUE INDEX "currencies_code_unique" on "currencies" ("code");
CREATE TABLE IF NOT EXISTS "tariffs" ("id" integer primary key autoincrement not null, "meter_id" integer not null, "currency_id" integer not null, "pricing_model" varchar not null, "base_rate" numeric not null, "service_fee" numeric, "effective_from" datetime not null, "effective_to" datetime, "notes" text, "created_at" datetime, "updated_at" datetime, foreign key("meter_id") references "meters"("id") on delete cascade, foreign key("currency_id") references "currencies"("id") on delete restrict);
CREATE INDEX "tariffs_meter_id_effective_from_index" on "tariffs" ("meter_id", "effective_from");
CREATE INDEX "tariffs_meter_id_effective_to_index" on "tariffs" ("meter_id", "effective_to");
CREATE UNIQUE INDEX "tariffs_meter_from_unique" on "tariffs" ("meter_id", "effective_from");
CREATE TABLE IF NOT EXISTS "address_user" ("address_id" integer not null, "user_id" integer not null, "created_at" datetime, "updated_at" datetime, foreign key("address_id") references "addresses"("id") on delete cascade, foreign key("user_id") references "users"("id") on delete cascade);
CREATE UNIQUE INDEX "address_user_address_id_user_id_unique" on "address_user" ("address_id", "user_id");
CREATE INDEX "address_user_address_id_index" on "address_user" ("address_id");
CREATE INDEX "address_user_user_id_index" on "address_user" ("user_id");
CREATE TABLE IF NOT EXISTS "addresses" ("id" integer primary key autoincrement not null, "city" varchar not null, "address" varchar not null, "house_number" varchar not null, "apartment_number" varchar, "zip_code" varchar not null, "created_at" datetime, "updated_at" datetime);
